& "$PSScriptRoot\..\gitmodules\mod-installer\build_all.ps1" `
  -Version "2.0.0" `
  -PreReleaseVersion "beta.1" `
  -OutputFilePrefix "MOP_1.0c" `
  -ModName "Mistake of Pythagoras 1.0c" `
  -ModFolder "MOP" `
  -ModFilesPath "$PSScriptRoot\..\game" `
  -ModBaseFilesUrl "https://github.com/HL2-Mods-Legacy-Project/hl2-legacy-registry/releases/download/mistake-of-pythagoras/MOP-1.0c-Original.zip" `
  -ModBaseFilesUrlHash "50d8b4f7bc0395de22fa9c33e72bd032cf1b44193f6ffb60091d34bfa34e51ed" `
  -ModReadmePath "readme.txt" `
  -PublishPath "$PSScriptRoot\..\artifacts\publish"
